### ISSUE TITLE
Routing issues

### ISSUE THREAD

**Issue by Peter9192** [eucp-project/storyboards#6]
The landing page on GH pages is hosted `eucp-project.github.io/usecases`. The path to a single use case is `eucp-project.github.io/usecases/usecase_0/panel_1`, but navigating directly to that page on GH returns a 404.

**Comment by Peter9192** [comment]
Seems to be the issue described here: https://medium.com/geekculture/github-pages-with-dynamic-routes-40f512900efa

**Comment by Peter9192** [comment]
In addition, the base url is not rendered correctly in the generated URLs

**Comment by geek-yang** [comment]
The built-in `:link=` function in the vueper slider component can not deal with the redirection for the routing in Nuxt. It is explained in this [post](https://githubmemory.com/repo/antoniandre/vueper-slides/issues/107). To enable this feature, we still need to use the `NuxtLink` and load the image without using the vueper slider built-in function (this is explained in the documentation of vueper slider, section [Complex Slide Title & Content](https://antoniandre.github.io/vueper-slides/#Complex%20Slide%20Title%20&%20Content)).
