### ISSUE TITLE
Feedback to story on hydrological impacts

### ISSUE THREAD

**Issue by Peter9192** [eucp-project/storyboards#66]
The story on hydrological impacts received attention from users, and they've been kind enough to provide some comments.

- The application could include some information about the value provided
- The performance-based weighting diagram is hard to understand. For example, the meaning of the blue horizontal bars and abbreviations such as NM7Q are not explained.
- Some figures are quite scientific and difficult to  understand for a policy audience. In general, it would help if all abbreviations are explained. Suggestion: the "blue/red" figure could perhaps be presented as a thematic map.
- Is the message that we should use bias corrected climate model input?

Would it be possible to update the storyboard based on (some of) these comments, or can we provide an answer here? I'd be happy to help implement the changes.

**Comment by sperna** [comment]
I updated the storyboard and will still add a link to the data. In line with the points mentioned above. I do not plan to change the table with the red/blue. I did include additional description.

To be honoust there is not yet a real stakeholder value - in that sence it is indeed more a scientific exercise, 
However I indicated that we worked together with end-user JRC.

**Comment by Peter9192** [comment]
Thanks for the response. Nothing wrong with scientific exercises! I'll have a look at the changes (they're in #73) and add the updated figures to the pull request.

**Comment by Peter9192** [comment]
I created #74 to update the figures.

**Comment by Peter9192** [comment]
Project finished with latest version of stories.
